---
- name: jenkins installation
  hosts: all
  become: true
  vars:
    jenkins_port: 8060
  tasks:
    - name: going to update the package
      apt:
        name: '*'
        state: present
    - name: installing the java and JDK
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - default-jre
        - default-jdk

    - name: Ensure the Jenkins is added to repo
      apt_key:
          url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
          state: present

    - name: saving the file 

      ansible.builtin.shell: nohup sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list' &
    - name: going to update the package
      apt:
        name: '*'
        state: present
    
    - name: changing the port number 
      template:
        src: ./jenkins.j2
        dest: /etc/default/jenkins
        mode: 0777

    - name: ensure the Jenkins is installed 
      apt:
        name: jenkins
        state: present
        update_cache: yes
    - name: changing port number
      ansible.builtin.shell: sudo sed -i -e 's/Environment="JENKINS_PORT=[0-9]\+"/Environment="JENKINS_PORT=8060"/' /usr/lib/systemd/system/jenkins.service
    - name: reload the systemd
      ansible.builtin.shell: sudo systemctl daemon-reload
    - name: restart the jenkins
      service:
        name: jenkins
        state: restarted
  

    

    
    